spring.application.name=Bookhub

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bookhub;integratedSecurity=false;encrypt=false;trustServerCertificate=false
spring.datasource.username=sa
spring.datasource.password=Pa$$w0rd
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
logging.level.sql=debug
